Update core_modeling_sprocket.py
fix the Proxy class, it's a trick for Handle_xxx-like classes
and line 225 at @tpaviot 's branch
```
if (round_circle_2d_1.Position().Location().Coord()[1] >= 0):
```
with error
```
TypeError: 'gp_XY' object does not support indexing
```